### ISSUE TITLE
ArgumentException when mapping flattens a many-to-many collection

### ISSUE THREAD

**Issue by csboling** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#11]
[Here](https://github.com/csboling/automapper-flattened-datasource/) is a project with a test that fails, and some similar usages which pass.

My mapping contains a collection which maps a many-to-many relationship into a collection property on the DTO that looks like a one-to-many relationship, "flattening out" the `LibraryBook` join table model:

```csharp
class Library
{
    . . .

    public List<LibraryBook> LibraryBooks { get; set; }
}

class LibraryBook
{
    . . .

    public Library Library { get; set; }

    public Book Book { get; set; }
}

class LibraryDto
{
    . . .

    public List<BookDto> Books { get; set; }
}

cfg.CreateMap<Library, LibraryDto>()
      .ForMember(
            dst => dst.Books,
            opt => opt.MapFrom(src => src.LibraryBooks.Select(lb => lb.Book)));
```

This mapping works until attempting a query expression which references the flattened collection:

```csharp
db.Set<Library>()
    .UseAsDataSource(this.Mapper)
    .For<LibraryDto>()
    .Where(l => l.Books.Any())
    .ToList();
```

In this case an exception is thrown during expression mapping:

```
 System.ArgumentException : 
Expression of type 'System.Func`2[automapper_flattened_datasource.Book,automapper_flattened_datasource.Book]' cannot be used for 
parameter of type 'System.Func`2[automapper_flattened_datasource.LibraryBook,automapper_flattened_datasource.Book]' 
of method 'System.Collections.Generic.IEnumerable`1[automapper_flattened_datasource.Book] Select[LibraryBook,Book]
(System.Collections.Generic.IEnumerable`1[automapper_flattened_datasource.LibraryBook], System.Func`2[automapper_flattened_datasource.LibraryBook,automapper_flattened_datasource.Book])'
Parameter name: arg1
Stack Trace:
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambdaExpression[T](Expression`1 expression)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedMethodCall(MethodCallExpression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceInjectedQueryProvider`2.ConvertDestinationExpressionToSourceExpression(Expression expression)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceInjectedQueryProvider`2.Execute[TResult](Expression expression)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

If I read the exception message correctly, it seems that it is not passing the expression I supply for `MapFrom` when dynamically building a new `Select` expression.

Using an `.Any()` call like this works with `.UseAsDataSource()` when using a mapping that maps from a simple collection on the domain object to a collection on the DTO. This also works when using `.ProjectTo<LibraryDto>()` instead of `.UseAsDataSource()`, but in that case EF cannot translate the resulting projection expression to SQL.

**Comment by TylerCarlson1** [comment]
It's probably trying to translate `lb => lb.Book` instead of leaving that part alone.

It has nothing to do with `Any()` but has to do with lambda translation using Books mapping.
That lambda expression can 't be translated into SQL either because the lambda is a Function and not an Expression of a Function.

Having a mapping from LibraryBook to BookDto instead of Book to Book would cause `Any()` to start working and even use ProjectTo with SQL translation.  The only issue is you would need to map every property out.

**Comment by BlaiseD** [comment]
You could also consider using your own helpers as described [here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping).

In your case the following works with the DTO expression:
```c#
        [Fact]
        public void ThenWhereAny()
        {
            using (var db = new ExampleContext(this.Connection))
            {
                var before = db.Set<Library>()
                    .Where(l => l.LibraryBooks.Select(lb => lb.Book).Any())
                    .UseAsDataSource(this.Mapper)
                    .For<LibraryDto>()
                    .ToList();

                var after = db.Set<Library>().GetItems<LibraryDto, Library>(this.Mapper, l => l.Books.Any()).ToList();

                Assert.Equal(
                    before.Select(l => l.Id),
                    after.Select(l => l.Id));
            }
        }

    internal static class Helpers
    {
        public static ICollection<TModel> GetItems<TModel, TData>(this IQueryable<TData> query, AutoMapper.IMapper mapper,
            Expression<Func<TModel, bool>> filter = null,
            Expression<Func<IQueryable<TModel>, IQueryable<TModel>>> queryFunc = null,
            IEnumerable<Expression<Func<TModel, object>>> includeProperties = null)
        {
            //Map the expressions
            Expression<Func<TData, bool>> f = mapper.MapExpression<Expression<Func<TData, bool>>>(filter);
            Func<IQueryable<TData>, IQueryable<TData>> mappedQueryFunc = mapper.MapExpression<Expression<Func<IQueryable<TData>, IQueryable<TData>>>>(queryFunc)?.Compile();
            ICollection<Expression<Func<TData, object>>> includes = mapper.MapIncludesList<Expression<Func<TData, object>>>(includeProperties);

            if (filter != null)
                query = query.Where(f);

            //if (includes != null)
                //query = includes.Aggregate(query, (q, next) => q.Include(next));

            //Call the store
            ICollection<TData> result = mappedQueryFunc != null ? mappedQueryFunc(query).ToList() : query.ToList();

            //Map and return the data
            return mapper.Map<IEnumerable<TData>, IEnumerable<TModel>>(result).ToList();
        }
    }
```

**Comment by csboling** [comment]
Okay, so it sounds like maybe this is the approach I should take in general: 
* take a dynamically built expression `userExpr` (based on user input) in terms of DTO types
* map it (`MapExpression(userExpr)`) back to an expression `domainExpr` on domain objects
* apply a `Where(domainExpr)` operator on the domain-side queryable with the mapped expression
* use `ProjectTo` to take care of `Select`ing only the columns needed for the DTO.

I can confirm that this works (and is evaluated server-side) in this particular `Any()` case:
```csharp
[Fact]
public void UseAsDataSource_MapExpression()
{
    using (var db = new ExampleContext(this.Connection))
    {
        var before = db.Set<Library>()
            .Where(l => l.LibraryBooks.Any())
            .ProjectTo<LibraryDto>(configuration: this.Mapper.ConfigurationProvider)
            .ToList();

        Expression<Func<LibraryDto, bool>> dtoExpr = l => l.Books.Any();
        Expression<Func<Library, bool>> domainExpr = this.Mapper.MapExpression<Expression<Func<Library, bool>>>(dtoExpr);

        var after = db.Set<Library>()
            .Where(domainExpr)
            .ProjectTo<LibraryDto>(configuration: this.Mapper.ConfigurationProvider)
            .ToList();

        Assert.Equal(
            before.Select(l => l.Id),
            after.Select(l => l.Id));
    }
}
```

Awesome! I think this should make issues I've been having a lot easier to debug since I can inspect the expression after mapping, and I can also inspect the whole expression tree in the case of an SQL translation failure, whereas `UseAsDataSource` was giving me kind of opaque `LibraryDto[]` expressions. 

Since this works with `MapExpression` I'll close the issue. Thanks for the pointers.
