### ISSUE TITLE
OData integration fail with navigation property

### ISSUE THREAD

**Issue by Luke-1988** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#23]
Hi there,

I am using AutoMapper 7.0.1 with EF Core 2.1 and I am trying to write a basic OData integration. This is my working code:

```
var _query = this.IUnitOfWork.IDataCrmRepository.contacts
                                .Where(w => w.org_id == config_org_id)
                                .UseAsDataSource(this.IMapper.ConfigurationProvider)
                                .For<DTO.contact>()
                                ;
// now order by optional navigation property (address) which may be null    
_query = _query.OrderBy(o => o.address.city);

return _query.ToArray();
```

So far so good. When I replace hardcoded OrdeBy with ODataQueryOptions<T> like this:

```
// _query = _query.OrderBy(o => o.address.city);
_query = options.ApplyTo(_query) as IQueryable<DTO.contact>;
```

When using with first-level property like GET /api/contacts?$orderby=fullname 
still working.

Problem comes, when I request GET /api/contacts?$orderby=address/city
I get error:

```
System.InvalidOperationException: Nullable object must have a value.
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in C:\projects\EFCore.PG\src\EFCore.PG\Storage\Internal\NpgsqlExecutionStrategy.cs:line 51
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

Address is optional and in some cases null. However, interesting is, when I manually update database to ensure that all contact have a address (for testing purposes), request does not fail and I get properly sorted result (by address.city)

Thanks for any advice!

**Comment by BlaiseD** [comment]
Isn't there an expand clause used with OData and navigation properties?  There are known issues with expansion and UseAsDataSource though.

There are examples [here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/3) and [here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/10) showing how to use retrieve the query expressions from OData and use them with the expression mapper directly - more flexible but less easy to use as UseAsDataSource.

So you have options.

**Comment by Luke-1988** [comment]
Thanks for your reply! As I wrote: 

> Address is optional and in some cases null. However, interesting is, when I manually update database to ensure that all contact have a address (for testing purposes), request does not fail and I get properly sorted result (by address.city)

Request fails when some of contacts have no relational address. When I manually assign an address to contact in database ( `UPDATE contacts SET addressID = .. WHERE addressID IS NULL` ), request will succeed, without any other modification (so no $expand is used)

Also, when I order hardcoded, bypassing OData, like this:

> // now order by optional navigation property (address) which may be null    
_query = _query.OrderBy(o => o.address.city);

request will succeed in same conditions (some addresses are null)

In my opinion, this is a bug. 

I am going to try same code on entity model, not on DTO. This will tell us if it has anything to do with AutoMapper.

**Comment by BlaiseD** [comment]
I'm sure it is a bug.  There are known issues with UseAsDataSource and navigation properties. Options:

- Download and reference the project locally, locate the bug and create a PR.
- Try the expression mapper.

**Comment by BlaiseD** [comment]
@jbogard , @TylerCarlson1 ,

What do think about a new repository for parsing [ODataQueryOptions](https://github.com/BlaiseD/AutoMapper.ODataExtensions)?  It solves the expansion issues and wraps the functionality.

One question is how to handle the multiple frameworks. I'm not seeing how to reduce the number of projects i.e. a lot of shared code but the dependencies call for separate projects.  WebAPI v5 requires **Microsoft.AspNet.OData** and the others need **Microsoft.AspNetCore.OData**. You'd need to detect AspNetCore vs WebApi (both full framework) from the referenced project.  I don't know if that's possible.   Thoughts?

- WebApi v5 with EF6
- AspNetCore (Full Framework) with EF6
- AspNetCore (.NetCore) with EFCore


The queries all seem to work:
```
http://localhost:16324/opstenant?$top=5&$expand=Buildings&$filter=Name eq 'One'&$orderby=Name desc
http://localhost:16324/opstenant?$top=5&$expand=Buildings&$filter=Name ne 'One'&$orderby=Name desc
http://localhost:16324/opstenant?$filter=Name eq 'One'
http://localhost:16324/opstenant?$top=5&$expand=Buildings&$orderby=Name desc
http://localhost:16324/opstenant?$orderby=Name desc
http://localhost:16324/opstenant?$orderby=Name desc&$count=true
http://localhost:16324/opstenant?$top=5&$filter=Name eq 'One'&$orderby=Name desc&$count=true
http://localhost:16324/opstenant?$top=5&$select=Name, Identity
http://localhost:16324/opstenant?$top=5&$expand=Buildings&$filter=Name ne 'One'&$orderby=Name desc
http://localhost:16324/opstenant?$top=5&$expand=Buildings($expand=Builder($expand=City))&$filter=Name ne 'One'&$orderby=Name desc

http://localhost:16324/corebuilding?$top=5&$expand=Builder,Tenant&$filter=name ne 'One L1'&$orderby=Name desc
http://localhost:16324/corebuilding?$top=5&$expand=Builder($expand=City),Tenant&$filter=name ne 'One L2'&$orderby=Name desc
```

**Comment by TylerCarlson1** [comment]
I don't use the ODataQuery options so I don't know how to feel about it personally.

**Comment by BlaiseD** [comment]
ok - I'll just rename and keep it.

**Comment by florin103** [comment]
Hi guys,
is there a good example on how to use ODataQueryOptions with Automapper and EF6?
I'm kind of puzzled between UseAsDataSource and ProjectTo. 

thanks,
Florin

**Comment by BlaiseD** [comment]
There are threads in this [forum](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/3) also a [repo here](https://github.com/BlaiseD/LogicBuilder.OData) which could help.
