### ISSUE TITLE
Expression of type 'System.DateTime' cannot be used for constructor parameter of type 'System.DateTimeOffset'

### ISSUE THREAD

**Issue by awilinsk** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#7]
I'm using Web API OData framework and using AutoMapper to map NHibernate domain objects to DTOs. When using the UseAsDataSource extension method, I get the following error:

System.ArgumentException
  HResult=0x80070057
  Message=Expression of type 'System.DateTime' cannot be used for constructor parameter of type 'System.DateTimeOffset'
  Source=<Cannot evaluate the exception source>
  StackTrace: at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at AutoMapper.ConstructorMap.NewExpression(Expression instanceParameter)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.DestinationConstructorExpression(TypeMap typeMap, Expression instanceParameter)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps, TypeMap& typeMap)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.Impl.MappedTypeExpressionBinder.BindMappedTypeExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.Impl.MappedTypeExpressionBinder.Build(IConfigurationProvider configuration, PropertyMap propertyMap, TypeMap propertyTypeMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.<>c__DisplayClass17_0.<CreateMemberBindings>g__CreateMemberBinding|0(PropertyMap propertyMap)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps, TypeMap& typeMap)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.QueryableExtensions.ExpressionBuilder.GetMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceInjectedQueryProvider`2.Execute[TResult](Expression expression)
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.GetEnumerator()
   at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.System.Collections.IEnumerable.GetEnumerator()
   at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at System.Web.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)

I have created explicit mappings for DateTime? to DateTimeOffset?
c.CreateMap<DateTime?, DateTimeOffset?>().ConvertUsing(x => (DateTimeOffset?)x);

This error only comes up when using the UseAsDataSource (and I would assume the ProjectTo methods as well). If I retrieve the full source entity list, the mapping works flawlessly.

**Comment by BlaiseD** [comment]
It's easier to help with a failing sample. Please include the code here, create a gist or add a repo [here](https://github.com/awilinsk?tab=repositories) producing the exception.

**Comment by awilinsk** [comment]
OK. I have created a sample solution with several different scenarios between DateTime and DateTimeOffset. It seems there are a few different issues around mapping between these types. https://github.com/awilinsk/UseAsDataSourceIssue

**Comment by BlaiseD** [comment]
What happens if you map the members?
```csharp
                c.CreateMap<Order, OrderModel>()//DateTime to DateTimeOffset
                .ForMember(x => x.OrderDate, o => o.MapFrom(s => new DateTimeOffset(s.OrderDate, TimeZoneInfo.Local.GetUtcOffset(s.OrderDate))))
                .ForMember(x => x.ShipDate, o => o.MapFrom(s => s.ShipDate.HasValue ? new DateTimeOffset(s.ShipDate.Value, TimeZoneInfo.Local.GetUtcOffset(s.ShipDate.Value)) : (DateTimeOffset?)null))
                .ReverseMap()//DateTimeOffset to dateTime
                .ForMember(x => x.OrderDate, o => o.MapFrom(s => ConvertOffsetToDateTime(s.OrderDate)))
                .ForMember(x => x.ShipDate, o => o.MapFrom(s => s.ShipDate.HasValue ? ConvertOffsetToDateTime(s.ShipDate.Value) : (DateTime?)null));

                //c.CreateMap<DateTime, DateTimeOffset>();
                //c.CreateMap<DateTime?, DateTimeOffset?>();

        private static DateTime ConvertOffsetToDateTime(DateTimeOffset offSet)
        {
            return offSet.DateTime;
        }
```
or however you've designed the conversions?

**Comment by awilinsk** [comment]
That does work. I did try the MapFrom before, but was just doing a explicit cast. Checking for HasValue and creating a DateTimeOffset worked, even using the OData $select.

The DateTime to DateTimeOffset (and reverse) isn't as straight forward as I would expect. I know it's not a primitive type, but I would think there would be built in support. Especially since OData uses DateTimeOffset.

Thank you for the help.

**Comment by BlaiseD** [comment]
np
