### ISSUE TITLE
No reference type (parent of) UserId is available to map as an include.

### ISSUE THREAD

**Issue by icnocop** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#71]
Hi.

When I try to map a property of one type to another, an `InvalidOperationException` exception is thrown with the message `No reference type (parent of) UserId is available to map as an include.`.

For example, add this test in `.\tests\AutoMapper.Extensions.ExpressionMapping.UnitTests\XpressionMapperTests.cs` and run it.
```
        [Fact]
        public void Map_basic_includes_list()
        {
            //Arrange
            ICollection<Expression<Func<UserModel, object>>> selections = new List<Expression<Func<UserModel, object>>>() { s => s.Id, s=> s.AccountName };

            //Act
            IList<Expression<Func<User, object>>> selectionsMapped = mapper.MapIncludesList<Expression<Func<User, object>>>(selections).ToList();
            List<object> accounts = Users.Select(selectionsMapped[0]).ToList();
            List<object> branches = Users.Select(selectionsMapped[1]).ToList();

            //Assert
            Assert.True(accounts.Count == 2 && branches.Count == 2);
        }
```

Result:
```
System.InvalidOperationException : The mapped member UserId is of type System.Int32 and a child of the parameter type AutoMapper.Extensions.ExpressionMapping.UnitTests.User.  No reference type (parent of) UserId is available to map as an include.
at AutoMapper.Extensions.ExpressionMapping.FindMemberExpressionsVisitor.VisitMember(MemberExpression node) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\FindMemberExpressionsVisitor.cs:line 55
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.Extensions.ExpressionMapping.MapIncludesVisitor.<VisitMember>g__GetMemberExpression|2_2(FindMemberExpressionsVisitor visitor, Expression mappedExpression) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\MapIncludesVisitor.cs:line 71
   at AutoMapper.Extensions.ExpressionMapping.MapIncludesVisitor.<VisitMember>g__GetMappedMemberExpression|2_0(Expression parentExpression, List`1 propertyMapInfoList, <>c__DisplayClass2_0& ) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\MapIncludesVisitor.cs:line 44
   at AutoMapper.Extensions.ExpressionMapping.MapIncludesVisitor.VisitMember(MemberExpression node) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\MapIncludesVisitor.cs:line 35
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.Extensions.ExpressionMapping.XpressionMapperVisitor.VisitUnary(UnaryExpression node) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\XpressionMapperVisitor.cs:line 232
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.Extensions.ExpressionMapping.MapperExtensions.<MapExpression>g__MapBody|5_1[TDestDelegate](Dictionary`2 typeMappings, XpressionMapperVisitor visitor, <>c__DisplayClass5_0`1& ) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\MapperExtensions.cs:line 89
   at AutoMapper.Extensions.ExpressionMapping.MapperExtensions.<MapExpression>g__CreateVisitor|5_0[TDestDelegate](Dictionary`2 typeMappings, <>c__DisplayClass5_0`1& ) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\MapperExtensions.cs:line 86
   at AutoMapper.Extensions.ExpressionMapping.MapperExtensions.MapExpression[TDestDelegate](IConfigurationProvider configurationProvider, LambdaExpression expression, Type typeSourceFunc, Type typeDestFunc, Func`3 getVisitor) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\MapperExtensions.cs:line 83
   at AutoMapper.Extensions.ExpressionMapping.MapperExtensions.MapExpression[TDestDelegate](IMapper mapper, LambdaExpression expression, Func`3 getVisitor) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\MapperExtensions.cs:line 66
   at AutoMapper.Extensions.ExpressionMapping.MapperExtensions.MapExpressionAsInclude[TDestDelegate](IMapper mapper, LambdaExpression expression) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\MapperExtensions.cs:line 134
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AutoMapper.Extensions.ExpressionMapping.MapperExtensions.MapIncludesList[TDestDelegate](IMapper mapper, IEnumerable`1 collection) in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\src\AutoMapper.Extensions.ExpressionMapping\MapperExtensions.cs:line 200
   at AutoMapper.Extensions.ExpressionMapping.UnitTests.XpressionMapperTests.Map_basic_includes_list() in C:\github\icnocop\AutoMapper.Extensions.ExpressionMapping\tests\AutoMapper.Extensions.ExpressionMapping.UnitTests\XpressionMapperTests.cs:line 29
```

Thank you.

**Comment by BlaiseD** [comment]
What's your expected result from mapping the Id property?

I think your intended [usage is incorrect](https://docs.automapper.org/en/stable/Expression-Translation-(UseAsDataSource).html#mapping-flattened-properties-to-navigation-properties).

**Comment by icnocop** [comment]
Thank you for the quick reply.

That's the same error I get when I try to map an OData Client `DataServiceQuery<T>` expression.

For example
1. Use the same sample code in https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/70#issue-616421423.
2. Add the `AutoMapper.AspNet.OData.EF6` nuget package to the `PublicWebApplication` project.
3. Replace line 34 in `.\PublicWebApplication\Controllers\PersonBsController.cs` with:
`return client.PersonAs.Get(mapper, options).AsQueryable();`

The properties of `PersonB` get added to the `includeExpressions` variable:
![includeExpressions](https://user-images.githubusercontent.com/507649/81848078-6af66b80-9509-11ea-99a8-667068043f95.png)

I expected those properties to be mapped to `PersonA`, specifically the `PersonAId` property to map to the `PersonBId` property.

Thank you.

**Comment by BlaiseD** [comment]
You may want to create an issue in the [OData](https://github.com/AutoMapper/AutoMapper.Extensions.OData) repo then.  Please include the query, expansions etc - so anyone can build, run and see it fail.

The InvalidOperationException is behaving as designed.

**Comment by icnocop** [comment]
Ok, thank you for the follow up.

**Comment by BlaiseD** [comment]
ok - also puzzled by all the literal types as expansions.
